### ISSUE TITLE
node-newrelic incompatible with Bluebird

### ISSUE THREAD

**Issue by mgartner** [lob/hapi-new-relic-transaction-patch#2]
Unfortunately, this patch does not remedy the issue fully. After diving deeper, it appears the `/*` routes are reported because `node-newrelic` is incompatible with Bluebird.

I've reached out to New Relic support about this, and will update when I hear back.

**Comment by sgulseth** [comment]
Any news on this?

**Comment by mgartner** [comment]
NewRelic fixed the issue in [node-newrelic v1.25.5](https://github.com/newrelic/node-newrelic/releases/tag/v1.25.5).
